name: Build and deploy intranet production.

on:
  workflow_dispatch:
  push:
    branches: [production-intranet, master-intranet, main-intranet]
    paths-ignore:
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: helsingborg-stad/municipio-deploy/4.1@master
      with:
        deploy-host: ${{ secrets.DEPLOY_REMOTE_HOST_PROD_INTRA }}
        deploy-port: ${{ secrets.DEPLOY_REMOTE_PORT_PROD_INTRA }}
        deploy-host-path: ${{ secrets.DEPLOY_REMOTE_PATH_PROD_INTRA  }}
        deploy-host-backup-path: ${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_PROD_INTRA }}
        deploy-host-user: ${{ secrets.DEPLOY_REMOTE_USER_PROD_INTRA }}
        deploy-host-user-key: ${{ secrets.DEPLOY_KEY_PROD_INTRA }}
        deploy-host-web-server-user: ${{ secrets.WEB_SERVER_USER_PROD_INTRA }}
        deploy-host-pagecache-path: ${{ secrets.DEPLOY_LS_PAGECACHE_PATH }}
        php-version: ${{ secrets.PHP_VERSION }}
        kill-lsphp: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        acf-url: ${{ secrets.ACF_URL }}
        newrelic-app-id: ${{ secrets.NEWRELIC_APP_ID }}
        newrelic-api-key: ${{ secrets.NEWRELIC_API_KEY }}
        sentry-url: ${{ vars.SENTRY_URL }}
        sentry-org: ${{ vars.SENTRY_ORG }}
        sentry-version: ${{ vars.SENTRY_VERSION }}
        sentry-api-key: ${{ secrets.SENTRY_API_KEY }}
        sentry-env: prod
        tideways-api-key: ${{ secrets.TIDEWAYS_API_KEY_INTRANET }}
        tideways-env: ${{ secrets.TIDEWAYS_ENV_PROD }}
